version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "angular-eslint"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"
      ngrx:
        patterns:
          - "@ngrx/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
