/**
 * Placeholder for editors, Karma, and non-production builds. Production uses
 * `fileReplacements` with `build-info.prod.ts`, generated by `npm run build:prod`
 * (see tools/iverbs-builders/write-build-info.cjs).
 */
export const PACKAGE_VERSION = 'dev';
export const BUILD_TIME_ISO = '';
export const GIT_COMMIT = '';
