// Generated by tools/iverbs-builders/write-build-info.cjs — do not edit by hand
export const PACKAGE_VERSION = "2.1.0";
export const BUILD_TIME_ISO = "2026-03-25T10:01:26.140Z";
export const GIT_COMMIT = "bd6d401";
