// Generated by tools/iverbs-builders/write-build-info.cjs — do not edit by hand
export const PACKAGE_VERSION = "2.2.0";
export const BUILD_TIME_ISO = "2026-03-25T10:28:06.110Z";
export const GIT_COMMIT = "4b474bd";
